language: node_js
node_js:
- '4.0'
sudo: required
before_install:
- firefox --version 2>/dev/null
- chromium-browser --product-version
- sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run lint
- npm test
- node ./bin/bt.js http://www.browsertime.net -b firefox -n 2
notifications:
  slack:
    secure: Bo/bgmtFVGj6I2XnkvERfGnoM+t73WQSsP5eMlGM0jhUSKPqIc7Hf2zjYil3amMY3awFnoA6prILcMBzyUURj3jc5VRsWBCf6aQZ3bM+xzAcuTMcoiAKS7Ru1HQj1WY8G7VycDWuNeF8dCT0kt2QhcSneAUQ0qqyclWjcOK22kw=
